# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_segmntr_wrappers", use_symbols = TRUE, package_name = "segmntr")

#' @docType package
#' @usage NULL
#' @useDynLib segmntr, .registration = TRUE
NULL

#' Internal wrapper of vaporetto
#' @keywords internal
vaporetto <- function(x, model) .Call(wrap__vaporetto, x, model)

